[project]
name = "qsar-hepatotoxicity-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "liamdujon@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "rdkit>=2026.3.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "xgboost>=3.4.1",
]

[project.scripts]
qsar-hepatotoxicity-predictor = "qsar_hepatotoxicity_predictor:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
