data:
  raw_tox_khan_path: "data/01_raw/tox_khan.csv"
  raw_tox21_path: "data/01_raw/tox21_path.csv"
  clean_tox21_path: "data/03_processed/tox21_clean.csv"
  predictions_dir: "data/04_predictions/"

model:
  target_col: "Target"
  random_state: 42
  save_path: "models/qsar_hepatotoxicity_model.pkl"